name: Docker login
author: Patrick Hilgenstock
description: >-
  Assumes a OIDC role and performs a docker login with it
inputs:
  role:
    description: The aws role to assume e.g. github-actions-ecr-reader
    required: true
  region:
    description: The aws region to use for authentication e.g. eu-central-1
    required: true
  docker-hub-username:
    description: The username to use for docker hub authentication if a docker hub login is wanted
    required: false
  docker-hub-password:
    description: The password to use for docker hub authentication
    required: false

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ inputs.role }}
        aws-region: ${{ inputs.region }}
    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1
    - name: Login to Docker Hub
      if: ${{ inputs.docker-hub-username  && inputs.docker-hub-password}}
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker-hub-username }}
        password: ${{ inputs.docker-hub-password }}

